name: Deploy to AWS lambda function 

on:
  push:
    branches:
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: zip the code
      run: zip -r python.zip helloworld.py
    - name: list directory
      run: ls -la      
    - name: aws list
      run: aws --version
    - name: update lambda function
      run: aws lambda update-function-code --function-name  github-function --zip-file fileb://python.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "ap-south-1"

  